language: node_js

node_js:
    - "14"
before_install: cd nodejs
install:
    - npm install
after_success:
- echo "$DOCKERPASSWORD" | docker login --username="$DOCKERUSER" --password-stdin
- docker build -t $DEPLOYIMAGE:latest .
- docker push $DOCKERUSER/$DEPLOYIMAGE:latest