version: '3.6'

services:
  nodejs:
    image: zerongjob/docket-test:latest
    environment:
      DBHOST: ordersample-mysql
      DBUSER: root
      DBPASSWORD: dbpassword
      DBNAME: ZERONGJOB
      GOOGLEMAPAPIKEY : AIzaSyClfFPTSCVamqtUP4Lj4RQ93RtcIbVWNwk
      PORT: 8080
    ports:
      - 8080:8080

  ordersample-mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_PASSWORD: dbpassword
      MYSQL_ROOT_PASSWORD: dbpassword
    ports:
      - 3306:3306
    volumes:
    - ./data/:/docker-entrypoint-initdb.d
    - ./db/:/var/lib/mysql